src/Entity/RendezVous.php
<?php

namespace App\Entity;

use App\Repository\RendezVousRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RendezVousRepository::class)]
class RendezVous
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nom_patient = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $prenom_patient = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $service = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $num_tel = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email_patient = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $adresse = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $date_rdv = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $naissance = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $heure_res = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $status = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $sexe = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $date_actuelle = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $age = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $num_ref = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $motif = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomPatient(): ?string
    {
        return $this->nom_patient;
    }

    public function setNomPatient(string $nom_patient): self
    {
        $this->nom_patient = $nom_patient;

        return $this;
    }

    public function getPrenomPatient(): ?string
    {
        return $this->prenom_patient;
    }

    public function setPrenomPatient(string $prenom_patient): self
    {
        $this->prenom_patient = $prenom_patient;

        return $this;
    }

    public function getService(): ?string
    {
        return $this->service;
    }

    public function setService(string $service): self
    {
        $this->service = $service;

        return $this;
    }

    public function getNaissance(): ?string
    {
        return $this->naissance;
    }

    public function setNaissance(string $naissance): self
    {
        $this->naissance = $naissance;

        return $this;
    }

    public function getNumTel(): ?string
    {
        return $this->num_tel;
    }

    public function setNumTel(string $num_tel): self
    {
        $this->num_tel = $num_tel;

        return $this;
    }

    public function getEmailPatient(): ?string
    {
        return $this->email_patient;
    }

    public function setEmailPatient(string $email_patient): self
    {
        $this->email_patient = $email_patient;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getDateRdv(): ?string
    {
        return $this->date_rdv;
    }

    public function setDateRdv(string $date_rdv): self
    {
        $this->date_rdv = $date_rdv;

        return $this;
    }

    public function getHeureRes(): ?string
    {
        return $this->heure_res;
    }

    public function setHeureRes(string $heure_res): self
    {
        $this->heure_res = $heure_res;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getDateActuelle(): ?string
    {
        return $this->date_actuelle;
    }

    public function setDateActuelle(string $date_actuelle): self
    {
        $this->date_actuelle = $date_actuelle;

        return $this;
    }

    public function getAge(): ?string
    {
        return $this->age;
    }

    public function setAge(?string $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getNumRef(): ?string
    {
        return $this->num_ref;
    }

    public function setNumRef(?string $num_ref): self
    {
        $this->num_ref = $num_ref;

        return $this;
    }

    public function getMotif(): ?string
    {
        return $this->motif;
    }

    public function setMotif(?string $motif): self
    {
        $this->motif = $motif;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $matricule = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $numero_patient = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $telephone = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $adresse = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $sexe = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $date_actuelle = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $anneenaissance = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $moisnaissance = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $specialite = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: PlageHoraire::class)]
    private Collection $plageHoraires;

    public function __construct()
    {
        $this->plageHoraires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getMatricule(): ?string
    {
        return $this->matricule;
    }

    public function setMatricule(string $matricule): self
    {
        $this->matricule = $matricule;

        return $this;
    }

    public function getNumeroPatient(): ?string
    {
        return $this->numero_patient;
    }

    public function setNumeroPatient(string $numero_patient): self
    {
        $this->numero_patient = $numero_patient;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getDateActuelle(): ?string
    {
        return $this->date_actuelle;
    }

    public function setDateActuelle(string $date_actuelle): self
    {
        $this->date_actuelle = $date_actuelle;

        return $this;
    }

    public function getAnneenaissance(): ?string
    {
        return $this->anneenaissance;
    }

    public function setAnneenaissance(?string $anneenaissance): self
    {
        $this->anneenaissance = $anneenaissance;

        return $this;
    }

    public function getMoisnaissance(): ?string
    {
        return $this->moisnaissance;
    }

    public function setMoisnaissance(?string $moisnaissance): self
    {
        $this->moisnaissance = $moisnaissance;

        return $this;
    }

    public function getSpecialite(): ?string
    {
        return $this->specialite;
    }

    public function setSpecialite(?string $specialite): self
    {
        $this->specialite = $specialite;

        return $this;
    }

    /**
     * @return Collection<int, PlageHoraire>
     */
    public function getPlageHoraires(): Collection
    {
        return $this->plageHoraires;
    }

    public function addPlageHoraire(PlageHoraire $plageHoraire): self
    {
        if (!$this->plageHoraires->contains($plageHoraire)) {
            $this->plageHoraires->add($plageHoraire);
            $plageHoraire->setUser($this);
        }

        return $this;
    }

    public function removePlageHoraire(PlageHoraire $plageHoraire): self
    {
        if ($this->plageHoraires->removeElement($plageHoraire)) {
            // set the owning side to null (unless already changed)
            if ($plageHoraire->getUser() === $this) {
                $plageHoraire->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\RendezVous;
use App\Entity\PropertySearch;
use App\Services\MailerService;
use App\Form\PropertySearchType;
use App\Repository\RendezVousRepository;
use Doctrine\Persistence\ManagerRegistry;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class HomeController extends AbstractController
{
    #[Route('/rendez-vous', name: 'app_rendezvous')]
    public function index(): Response
    {
        return $this->render('home/rendezvous.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }

    #[Route('/mes_rendez-vous', name: 'app_mesrendezvous')]
    public function mesrendezvous(RendezVousRepository $rendezVousRepository, Request $request, PaginatorInterface $paginator): Response
    {
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);
        $users = $this->getUser();
        $userRdv = $rendezVousRepository->findUserRdv($users, $search);
        $rdv = $paginator->paginate(
            $userRdv,
            $request->query->getInt('page', '1'),
            5
        );
        return $this->render('home/mesrendezvous.html.twig', [
            'reservations' => $rdv,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/profil', name: 'app_profil')]
    public function profil(): Response
    {
        return $this->render('home/profil.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }

    #[Route('/', name: 'app_home')]
    public function home(): Response
    {
        return $this->render('home/home.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }

    #[Route('/home', name: 'app_homeac')]
    public function homeac(): Response
    {
        return $this->render('home/homeac.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }

    #[Route('/profil_patient/editer_mot_de_passe/modal', name: 'app_modal')]
    public function modal(): Response
    {
        return $this->render('home/modal.html.twig', [
            'controller_name' => 'HomeController',
        ]);
    }

    #[Route('/rendez-vous/recapitulatif', name: 'app_recapitulatif', methods: ['POST'])]

    public function recapitulatif(ManagerRegistry $doctrine, MailerService $mailer, Request $request): Response
    {
        $user = $this->getUser();
        $entityManager = $doctrine->getManager();
        $reservation = new RendezVous();
        $reservation->setNomPatient($request->get('nom_patient'));
        $reservation->setPrenomPatient($request->get('prenom_patient'));
        $reservation->setAdresse($request->get('adresse'));
        $reservation->setEmailPatient($request->get('email_patient'));
        $reservation->setNumTel($request->get('num_tel'));
        $reservation->setService($request->get('service'));
        $reservation->setStatus('A Venir');
        $reservation->setAge($request->get('age'));
        $reservation->setSexe($request->get('sexe'));
        $reservation->setMotif($request->get('motif'));
        $reservation->setDateRdv($request->get('date_rdv'));
        $reservation->setHeureRes($request->get('heure_res'));

        $initialep = $user->getPrenom();
        $initialep = substr($initialep, 0, 1);

        $initialen = $user->getNom();
        $initialen = substr($initialen, 0, 1);

        $nbr_rand = '';
        for ($i = 0; $i < 10; $i++)
            $nbr_rand .= rand(0, 9);
        $numreference = 'RV00 ' . $nbr_rand;
        $reservation->setNumRef($numreference);

        $today = date("l d F Y");
        $reservation->setDateActuelle($today);

        // tell Doctrine you want to (eventually) save the Product (no queries yet)
        $entityManager->persist($reservation);

        // actually executes the queries (i.e. the INSERT query)
        $entityManager->flush();

        $message = "votre reservation a ete prise en compte";
        $mailMessage = $reservation->getNomPatient() . ' ' . $reservation->getPrenomPatient() . ' ' . $message;
        $mailer->sendEmail(content: $mailMessage);

        // return $this->redirectToRoute('app_rendezVous');
        return $this->render('home/recapitulatif.html.twig', [
            'persons' => $reservation,
            'personsp' => $initialep,
            'personsn' => $initialen,
            'numreference' => $numreference,
            'today' => $today,
        ]);
    }
}

templates/home/recapitulatif.html.twig
{% extends 'headerallpatient.html.twig' %}

{% block title %}Connexion
{% endblock %}
{% block stylesheets%}
	<style>
		body {
			background-image: url({{asset('images/hero-bg.png')}});
			background-size: cover;
			background-attachment: fixed;
			min-height: 100%;
		}
		.wrapper .logo img {
			max-width: 25%;
		}
		.wrapper input:focus {
			box-shadow: none;
			border-color: #1fab89;
		}
		.fontuser input,
		select {
			padding-left: 35px !important;
		}
		.wrapper select:focus {
			box-shadow: none;
			border-color: #1fab89;
		}
		.wrapper .submit_btn {
			padding: 15px;
			font-weight: 500;
		}
		.wrapper .submit_btn:focus {
			box-shadow: none;
		}
		#container2 {
			width: 80%;
			margin-left: auto;
			margin-right: auto;
		}

		label span {
			color: red;
			font-size: 18px;
		}
		#formm {
			position: absolute;
			margin-top: 80px;
			width: 80%;
			margin-left: auto;
			margin-right: auto;
		}
		.fontuser {
			position: relative;
		}

		.fontuser i {
			position: absolute;
			left: 12px;
			top: 38px;
			color: gray;
		}
		p {
			margin-bottom: 0 !important;
		}
		.avatar {
			font-size: 16px;
			width: 3em;
			height: 3em;
			border-radius: 50%;
			background: #555555;
			display: inline-flex;
			align-items: center;
			justify-content: center;
		}

		.avatar::after {
			content: attr(data-label);
			font-family: "Readex Pro", sans-serif;
			color: #ffffff;
		}

		#alertee {
			background-color: inherit;
			border: none;
			padding-left: 0;
			padding-bottom: 0 !important;
			margin-bottom: 20px !important;
		}

		#precap {
			font-size: 28px;
			font-weight: 600;
		}

		#psrecap {
			font-size: 12px;
		}
		#drv {
			height: 40px;
			background-color: #F8F8F8;
			border-radius: 5px;
		}
		p i {
			margin-right: 8px;
		}
		#statusrecap {
			background-color: #DAD7D7;
			text-align: center;
			width: 78px;
			padding: 4px;
			border-radius: 5px;
		}
		#ref {
			text-align: right;
		}

		.fa-solid.fa-circle-info {
			color: #198754;
		}
		.bi.flex-shrink-0.me-2 {
			color: #198754;
		}
	</style>
{% endblock %}
{% block body %}

	<section class="wrapper">
		<div id="container2" class="col-sm-8  col-lg-9 col-xl-5">
			<form
				method="post" action="{{ path('app_recapitulatif') }}" id="formm" class="rounded bg-white shadow py-3 pb-5 px-4">

				{# <h3 class="text-dark fw-bolder fs-2 mb-4">Votre récapitulatif</h3> #}
				<div class="row">

					<div class="col-lg-4">
						<div class="card mb-4 rounded border border-light bg-light">
							<div class="card-body text-center">
								<div class="avatar" data-label="{{personsp}}{{personsn}}"></div>
								<h5 class="my-3">{{app.user.prenom}}
									{{app.user.nom}}</h5>
								<p class="text-muted mb-1">{{app.user.userIdentifier}}</p>
								<p class="text-muted mb-4">{{app.user.telephone}}</p>
								<div class="d-flex justify-content-center mb-2">
									<a href="/profil_patient" type="button" class="btn btn-success">Profil</a>
									<a href="/rendez-vous" type="button" class="btn btn-outline-success ms-1">
										<i class="fa-solid fa-circle-plus "></i>
										Rendez-vous</a>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-8">
						<div class="card mb-4 border-0">
							<div class="card-body p-0 mx-3 my-3">
								<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
									<symbol id="check-circle-fill" fill="currentColor" viewbox="0 0 16 16">
										<path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
									</symbol>
									<symbol id="info-fill" fill="currentColor" viewbox="0 0 16 16">
										<path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
									</symbol>
									<symbol id="exclamation-triangle-fill" fill="currentColor" viewbox="0 0 16 16">
										<path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
									</symbol>
								</svg>

								<div id="alertee" class="alert alert-success d-flex align-items-center" role="alert">
									<svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:">
										<use xlink:href="#check-circle-fill"/>
									</svg>
									<div></div>
								</div>
								<div class="row">
									<div class="col-md-7 ">
										<p>
											Rendez-vous confirmé
										</p>
									</div>
									<div class="col-md-5 ">
										<p id="ref" class="text-rigth">
											REF :
											{{numreference}}<br>
											<span>{{today}}</span>
										</p>
									</div>
								</div>
								<div class="row">
									<div class="col-md-9 w-100">
										<p id="precap" class="mb-0">Mercredi 28 Avril à 21h45</p>
									</div>
								</div>
								<div class="row">
									<div class="col-sm-9">
										<p id="psrecap" class="mb-4 my-2">NB: Veiller à ne pas manquer votre rendez-vous
										</p>
									</div>
								</div>
								<div id="drv" class="row mb-3">
									<div class="col-md-9">
										<i class="fa-light fa-memo-circle-info"></i>
										<p class="mb-4 my-2">
											<i class="fa-solid fa-circle-info"></i>Détails du rendez-vous</p>
									</div>
								</div>
								<div class="row">
									<div class="col-md-9 ">
										<p class="mb-2">
											<i class="fa-regular fa-user"></i>
											{{persons.prenomPatient}}
											{{persons.nomPatient}}
										</p>
									</div>
								</div>
								<div class="row">
									<div class="col-md-7 ">
										<p class="mb-2 text-truncate" style="overflow:auto">
											<i class="fa-regular fa-envelope"></i>
											{{persons.emailPatient}}
										</p>
									</div>
									<div class="col-md-5 ">
										<p class="mb-2">
											<i class="fa-solid fa-phone"></i>
											{{persons.numTel}}
										</p>
									</div>
								</div>
								<div class="row">
									<div class="col-md-7">
										<p class="mb-2 text-truncate" style="overflow:auto">
											<i class="fa-solid fa-location-dot"></i>
											{{persons.Adresse}}
										</p>
									</div>
									<div class="col-md-5 ">
										<p class="mb-2">
											<i class="fa-solid fa-venus-mars"></i>
											{{persons.Sexe}}
										</p>
									</div>
								</div>
								<div class="row">
									<div class="col-md-7">
										<p class="mb-2 text-capitalize">
											<i class="text-none fa-solid fa-truck-medical"></i>
											Service :
											{{persons.Service}}
										</p>
									</div>
									<div class="col-md-5">
										<p class="mb-2">
											<i class="fa-regular fa-calendar"></i>
											Age :
											{{persons.Age}}
										</p>
									</div>
								</div>
								<div class="row">
									<div class="col-md-7">
										<p class="mb-2">
											<i class="fa-regular fa-calendar-days"></i>
											{{persons.dateRdv}}
										</p>
									</div>

								</div>

								<div class="row">
									<div class="col-md-7 ">
										<p class="mb-2">
											<i class="fa-regular fa-clock"></i>
											{{persons.heureRes}}
										</p>
									</div>
									<div class="col-md-5">
										<p id="statusrecap" class="mb-2">
											{{persons.Status}}
										</p>
									</div>
								</div>
								<div class="row">
									<div class="col-md-9 ">
										<p class="mb-2">
											<i class="fa-solid fa-pen-to-square"></i>
											{{persons.motif}}
										</p>
									</div>
								</div>

								<div class="row">
									<div class="col-md-9 mt-4 p-0">
										<a href="/rendez-vous" type="button" class="btn btn-outline-success ms-1">
											<i class="fa-solid fa-circle-plus "></i>
											Nouveau Rendez-vous</a>
										<a href="/home" type="button" class="btn btn-danger">Quitter</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</form>
	</div>
</section>

<script>
	inputDate.min = new Date().toISOString().split("T")[0];

const avatars = document.querySelectorAll(".avatar");

avatars.forEach((a) => {
const charCodeRed = a.dataset.label.charCodeAt(0);
const charCodeGreen = a.dataset.label.charCodeAt(1) || charCodeRed;

const red = Math.pow(charCodeRed, 7) % 200;
const green = Math.pow(charCodeGreen, 7) % 200;
const blue = (red + green) % 200;

a.style.background = `rgb(${red}, ${green}, ${blue})`;
});
</script>{% endblock %}